/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateOptionArgs } from "./CreateOptionArgs";
import { UpdateOptionArgs } from "./UpdateOptionArgs";
import { DeleteOptionArgs } from "./DeleteOptionArgs";
import { OptionFindManyArgs } from "./OptionFindManyArgs";
import { OptionFindUniqueArgs } from "./OptionFindUniqueArgs";
import { Option } from "./Option";
import { ProductCartOptionFindManyArgs } from "../../productCartOption/base/ProductCartOptionFindManyArgs";
import { ProductCartOption } from "../../productCartOption/base/ProductCartOption";
import { SuboptionFindManyArgs } from "../../suboption/base/SuboptionFindManyArgs";
import { Suboption } from "../../suboption/base/Suboption";
import { Product } from "../../product/base/Product";
import { OptionService } from "../option.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Option)
export class OptionResolverBase {
  constructor(
    protected readonly service: OptionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Option",
    action: "read",
    possession: "any",
  })
  async _optionsMeta(
    @graphql.Args() args: OptionFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Option])
  @nestAccessControl.UseRoles({
    resource: "Option",
    action: "read",
    possession: "any",
  })
  async options(@graphql.Args() args: OptionFindManyArgs): Promise<Option[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Option, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Option",
    action: "read",
    possession: "own",
  })
  async option(
    @graphql.Args() args: OptionFindUniqueArgs
  ): Promise<Option | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Option)
  @nestAccessControl.UseRoles({
    resource: "Option",
    action: "create",
    possession: "any",
  })
  async createOption(@graphql.Args() args: CreateOptionArgs): Promise<Option> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        product: args.data.product
          ? {
              connect: args.data.product,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Option)
  @nestAccessControl.UseRoles({
    resource: "Option",
    action: "update",
    possession: "any",
  })
  async updateOption(
    @graphql.Args() args: UpdateOptionArgs
  ): Promise<Option | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          product: args.data.product
            ? {
                connect: args.data.product,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Option)
  @nestAccessControl.UseRoles({
    resource: "Option",
    action: "delete",
    possession: "any",
  })
  async deleteOption(
    @graphql.Args() args: DeleteOptionArgs
  ): Promise<Option | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ProductCartOption], {
    name: "productCartOptions",
  })
  @nestAccessControl.UseRoles({
    resource: "ProductCartOption",
    action: "read",
    possession: "any",
  })
  async resolveFieldProductCartOptions(
    @graphql.Parent() parent: Option,
    @graphql.Args() args: ProductCartOptionFindManyArgs
  ): Promise<ProductCartOption[]> {
    const results = await this.service.findProductCartOptions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Suboption], { name: "suboptions" })
  @nestAccessControl.UseRoles({
    resource: "Suboption",
    action: "read",
    possession: "any",
  })
  async resolveFieldSuboptions(
    @graphql.Parent() parent: Option,
    @graphql.Args() args: SuboptionFindManyArgs
  ): Promise<Suboption[]> {
    const results = await this.service.findSuboptions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "read",
    possession: "any",
  })
  async resolveFieldProduct(
    @graphql.Parent() parent: Option
  ): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
