/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BusinessTypeService } from "../businessType.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BusinessTypeCreateInput } from "./BusinessTypeCreateInput";
import { BusinessTypeWhereInput } from "./BusinessTypeWhereInput";
import { BusinessTypeWhereUniqueInput } from "./BusinessTypeWhereUniqueInput";
import { BusinessTypeFindManyArgs } from "./BusinessTypeFindManyArgs";
import { BusinessTypeUpdateInput } from "./BusinessTypeUpdateInput";
import { BusinessType } from "./BusinessType";
import { BusinessFindManyArgs } from "../../business/base/BusinessFindManyArgs";
import { Business } from "../../business/base/Business";
import { BusinessWhereUniqueInput } from "../../business/base/BusinessWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BusinessTypeControllerBase {
  constructor(
    protected readonly service: BusinessTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BusinessType })
  @nestAccessControl.UseRoles({
    resource: "BusinessType",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: BusinessTypeCreateInput
  ): Promise<BusinessType> {
    return await this.service.create({
      data: data,
      select: {
        description: true,
        id: true,
        image: true,
        name: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BusinessType] })
  @ApiNestedQuery(BusinessTypeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BusinessType",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<BusinessType[]> {
    const args = plainToClass(BusinessTypeFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        description: true,
        id: true,
        image: true,
        name: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BusinessType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BusinessType",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: BusinessTypeWhereUniqueInput
  ): Promise<BusinessType | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        description: true,
        id: true,
        image: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BusinessType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BusinessType",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: BusinessTypeWhereUniqueInput,
    @common.Body() data: BusinessTypeUpdateInput
  ): Promise<BusinessType | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          description: true,
          id: true,
          image: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BusinessType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BusinessType",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: BusinessTypeWhereUniqueInput
  ): Promise<BusinessType | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          description: true,
          id: true,
          image: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/business")
  @ApiNestedQuery(BusinessFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Business",
    action: "read",
    possession: "any",
  })
  async findManyBusiness(
    @common.Req() request: Request,
    @common.Param() params: BusinessTypeWhereUniqueInput
  ): Promise<Business[]> {
    const query = plainToClass(BusinessFindManyArgs, request.query);
    const results = await this.service.findBusiness(params.id, {
      ...query,
      select: {
        id: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/business")
  @nestAccessControl.UseRoles({
    resource: "BusinessType",
    action: "update",
    possession: "any",
  })
  async connectBusiness(
    @common.Param() params: BusinessTypeWhereUniqueInput,
    @common.Body() body: BusinessWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      business: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/business")
  @nestAccessControl.UseRoles({
    resource: "BusinessType",
    action: "update",
    possession: "any",
  })
  async updateBusiness(
    @common.Param() params: BusinessTypeWhereUniqueInput,
    @common.Body() body: BusinessWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      business: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/business")
  @nestAccessControl.UseRoles({
    resource: "BusinessType",
    action: "update",
    possession: "any",
  })
  async disconnectBusiness(
    @common.Param() params: BusinessTypeWhereUniqueInput,
    @common.Body() body: BusinessWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      business: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
