/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SuboptionService } from "../suboption.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SuboptionCreateInput } from "./SuboptionCreateInput";
import { SuboptionWhereInput } from "./SuboptionWhereInput";
import { SuboptionWhereUniqueInput } from "./SuboptionWhereUniqueInput";
import { SuboptionFindManyArgs } from "./SuboptionFindManyArgs";
import { SuboptionUpdateInput } from "./SuboptionUpdateInput";
import { Suboption } from "./Suboption";
import { ProductCartSuboptionFindManyArgs } from "../../productCartSuboption/base/ProductCartSuboptionFindManyArgs";
import { ProductCartSuboption } from "../../productCartSuboption/base/ProductCartSuboption";
import { ProductCartSuboptionWhereUniqueInput } from "../../productCartSuboption/base/ProductCartSuboptionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SuboptionControllerBase {
  constructor(
    protected readonly service: SuboptionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Suboption })
  @nestAccessControl.UseRoles({
    resource: "Suboption",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: SuboptionCreateInput): Promise<Suboption> {
    return await this.service.create({
      data: {
        ...data,

        option: data.option
          ? {
              connect: data.option,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        option: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Suboption] })
  @ApiNestedQuery(SuboptionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Suboption",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Suboption[]> {
    const args = plainToClass(SuboptionFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        option: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Suboption })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Suboption",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: SuboptionWhereUniqueInput
  ): Promise<Suboption | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        option: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Suboption })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Suboption",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: SuboptionWhereUniqueInput,
    @common.Body() data: SuboptionUpdateInput
  ): Promise<Suboption | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          option: data.option
            ? {
                connect: data.option,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          option: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Suboption })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Suboption",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: SuboptionWhereUniqueInput
  ): Promise<Suboption | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          option: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/productCartSuboptions")
  @ApiNestedQuery(ProductCartSuboptionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProductCartSuboption",
    action: "read",
    possession: "any",
  })
  async findManyProductCartSuboptions(
    @common.Req() request: Request,
    @common.Param() params: SuboptionWhereUniqueInput
  ): Promise<ProductCartSuboption[]> {
    const query = plainToClass(ProductCartSuboptionFindManyArgs, request.query);
    const results = await this.service.findProductCartSuboptions(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        position: true,
        price: true,

        productCartOptions: {
          select: {
            id: true,
          },
        },

        quantity: true,
        selected: true,

        suboption: {
          select: {
            id: true,
          },
        },

        total: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/productCartSuboptions")
  @nestAccessControl.UseRoles({
    resource: "Suboption",
    action: "update",
    possession: "any",
  })
  async connectProductCartSuboptions(
    @common.Param() params: SuboptionWhereUniqueInput,
    @common.Body() body: ProductCartSuboptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productCartSuboptions: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/productCartSuboptions")
  @nestAccessControl.UseRoles({
    resource: "Suboption",
    action: "update",
    possession: "any",
  })
  async updateProductCartSuboptions(
    @common.Param() params: SuboptionWhereUniqueInput,
    @common.Body() body: ProductCartSuboptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productCartSuboptions: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/productCartSuboptions")
  @nestAccessControl.UseRoles({
    resource: "Suboption",
    action: "update",
    possession: "any",
  })
  async disconnectProductCartSuboptions(
    @common.Param() params: SuboptionWhereUniqueInput,
    @common.Body() body: ProductCartSuboptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productCartSuboptions: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
