export enum EnumCuisineTypeName {
  Mexican = "Mexican",
  American = "American",
  Italian = "Italian",
  Chinese = "Chinese",
  Japanese = "Japanese",
  Indian = "Indian",
  Thai = "Thai",
  Coffee = "Coffee",
  FastFood = "FastFood",
  Brazilian = "Brazilian",
  Salad = "Salad",
  Sushi = "Sushi",
  Pizza = "Pizza",
  Burgers = "Burgers",
  Greek = "Greek",
  Sandwiches = "Sandwiches",
  Korean = "Korean",
  Desserts = "Desserts",
}
