/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProductCartService } from "../productCart.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductCartCreateInput } from "./ProductCartCreateInput";
import { ProductCartWhereInput } from "./ProductCartWhereInput";
import { ProductCartWhereUniqueInput } from "./ProductCartWhereUniqueInput";
import { ProductCartFindManyArgs } from "./ProductCartFindManyArgs";
import { ProductCartUpdateInput } from "./ProductCartUpdateInput";
import { ProductCart } from "./ProductCart";
import { ProductCartOptionFindManyArgs } from "../../productCartOption/base/ProductCartOptionFindManyArgs";
import { ProductCartOption } from "../../productCartOption/base/ProductCartOption";
import { ProductCartOptionWhereUniqueInput } from "../../productCartOption/base/ProductCartOptionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProductCartControllerBase {
  constructor(
    protected readonly service: ProductCartService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProductCart })
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: ProductCartCreateInput
  ): Promise<ProductCart> {
    return await this.service.create({
      data: {
        ...data,

        product: data.product
          ? {
              connect: data.product,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProductCart] })
  @ApiNestedQuery(ProductCartFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<ProductCart[]> {
    const args = plainToClass(ProductCartFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProductCart })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: ProductCartWhereUniqueInput
  ): Promise<ProductCart | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProductCart })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: ProductCartWhereUniqueInput,
    @common.Body() data: ProductCartUpdateInput
  ): Promise<ProductCart | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          product: data.product
            ? {
                connect: data.product,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          product: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProductCart })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: ProductCartWhereUniqueInput
  ): Promise<ProductCart | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          product: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/productCartOptions")
  @ApiNestedQuery(ProductCartOptionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProductCartOption",
    action: "read",
    possession: "any",
  })
  async findManyProductCartOptions(
    @common.Req() request: Request,
    @common.Param() params: ProductCartWhereUniqueInput
  ): Promise<ProductCartOption[]> {
    const query = plainToClass(ProductCartOptionFindManyArgs, request.query);
    const results = await this.service.findProductCartOptions(params.id, {
      ...query,
      select: {
        balance: true,
        createdAt: true,
        id: true,

        option: {
          select: {
            id: true,
          },
        },

        productCart: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/productCartOptions")
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "update",
    possession: "any",
  })
  async connectProductCartOptions(
    @common.Param() params: ProductCartWhereUniqueInput,
    @common.Body() body: ProductCartOptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productCartOptions: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/productCartOptions")
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "update",
    possession: "any",
  })
  async updateProductCartOptions(
    @common.Param() params: ProductCartWhereUniqueInput,
    @common.Body() body: ProductCartOptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productCartOptions: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/productCartOptions")
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "update",
    possession: "any",
  })
  async disconnectProductCartOptions(
    @common.Param() params: ProductCartWhereUniqueInput,
    @common.Body() body: ProductCartOptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productCartOptions: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
