/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProductCartService } from "../productCart.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductCartCreateInput } from "./ProductCartCreateInput";
import { ProductCartWhereInput } from "./ProductCartWhereInput";
import { ProductCartWhereUniqueInput } from "./ProductCartWhereUniqueInput";
import { ProductCartFindManyArgs } from "./ProductCartFindManyArgs";
import { ProductCartUpdateInput } from "./ProductCartUpdateInput";
import { ProductCart } from "./ProductCart";
import { ProductCartSuboptionFindManyArgs } from "../../productCartSuboption/base/ProductCartSuboptionFindManyArgs";
import { ProductCartSuboption } from "../../productCartSuboption/base/ProductCartSuboption";
import { ProductCartSuboptionWhereUniqueInput } from "../../productCartSuboption/base/ProductCartSuboptionWhereUniqueInput";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProductCartControllerBase {
  constructor(
    protected readonly service: ProductCartService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProductCart })
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: ProductCartCreateInput
  ): Promise<ProductCart> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProductCart] })
  @ApiNestedQuery(ProductCartFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<ProductCart[]> {
    const args = plainToClass(ProductCartFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProductCart })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: ProductCartWhereUniqueInput
  ): Promise<ProductCart | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProductCart })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: ProductCartWhereUniqueInput,
    @common.Body() data: ProductCartUpdateInput
  ): Promise<ProductCart | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProductCart })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: ProductCartWhereUniqueInput
  ): Promise<ProductCart | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/productCartSuboptions")
  @ApiNestedQuery(ProductCartSuboptionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProductCartSuboption",
    action: "read",
    possession: "any",
  })
  async findManyProductCartSuboptions(
    @common.Req() request: Request,
    @common.Param() params: ProductCartWhereUniqueInput
  ): Promise<ProductCartSuboption[]> {
    const query = plainToClass(ProductCartSuboptionFindManyArgs, request.query);
    const results = await this.service.findProductCartSuboptions(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        position: true,
        price: true,

        productCart: {
          select: {
            id: true,
          },
        },

        quantity: true,
        selected: true,

        suboption: {
          select: {
            id: true,
          },
        },

        total: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/productCartSuboptions")
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "update",
    possession: "any",
  })
  async connectProductCartSuboptions(
    @common.Param() params: ProductCartWhereUniqueInput,
    @common.Body() body: ProductCartSuboptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productCartSuboptions: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/productCartSuboptions")
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "update",
    possession: "any",
  })
  async updateProductCartSuboptions(
    @common.Param() params: ProductCartWhereUniqueInput,
    @common.Body() body: ProductCartSuboptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productCartSuboptions: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/productCartSuboptions")
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "update",
    possession: "any",
  })
  async disconnectProductCartSuboptions(
    @common.Param() params: ProductCartWhereUniqueInput,
    @common.Body() body: ProductCartSuboptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productCartSuboptions: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/products")
  @ApiNestedQuery(ProductFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "read",
    possession: "any",
  })
  async findManyProducts(
    @common.Req() request: Request,
    @common.Param() params: ProductCartWhereUniqueInput
  ): Promise<Product[]> {
    const query = plainToClass(ProductFindManyArgs, request.query);
    const results = await this.service.findProducts(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/products")
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "update",
    possession: "any",
  })
  async connectProducts(
    @common.Param() params: ProductCartWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/products")
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "update",
    possession: "any",
  })
  async updateProducts(
    @common.Param() params: ProductCartWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/products")
  @nestAccessControl.UseRoles({
    resource: "ProductCart",
    action: "update",
    possession: "any",
  })
  async disconnectProducts(
    @common.Param() params: ProductCartWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
