/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { OrderSummaryService } from "../orderSummary.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OrderSummaryCreateInput } from "./OrderSummaryCreateInput";
import { OrderSummaryWhereInput } from "./OrderSummaryWhereInput";
import { OrderSummaryWhereUniqueInput } from "./OrderSummaryWhereUniqueInput";
import { OrderSummaryFindManyArgs } from "./OrderSummaryFindManyArgs";
import { OrderSummaryUpdateInput } from "./OrderSummaryUpdateInput";
import { OrderSummary } from "./OrderSummary";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class OrderSummaryControllerBase {
  constructor(
    protected readonly service: OrderSummaryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OrderSummary })
  @nestAccessControl.UseRoles({
    resource: "OrderSummary",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: OrderSummaryCreateInput
  ): Promise<OrderSummary> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        deliveryPrice: true,
        deliveryPriceWithDiscount: true,
        discount: true,
        driverTip: true,
        driverTipRate: true,
        id: true,
        serviceFee: true,
        serviceFeeRate: true,
        serviceFeeWithDiscount: true,
        subtotal: true,
        subtotalWithDiscount: true,
        taxAfterDiscount: true,
        taxRate: true,
        taxWithDiscount: true,
        total: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [OrderSummary] })
  @ApiNestedQuery(OrderSummaryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "OrderSummary",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<OrderSummary[]> {
    const args = plainToClass(OrderSummaryFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        deliveryPrice: true,
        deliveryPriceWithDiscount: true,
        discount: true,
        driverTip: true,
        driverTipRate: true,
        id: true,
        serviceFee: true,
        serviceFeeRate: true,
        serviceFeeWithDiscount: true,
        subtotal: true,
        subtotalWithDiscount: true,
        taxAfterDiscount: true,
        taxRate: true,
        taxWithDiscount: true,
        total: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OrderSummary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OrderSummary",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: OrderSummaryWhereUniqueInput
  ): Promise<OrderSummary | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        deliveryPrice: true,
        deliveryPriceWithDiscount: true,
        discount: true,
        driverTip: true,
        driverTipRate: true,
        id: true,
        serviceFee: true,
        serviceFeeRate: true,
        serviceFeeWithDiscount: true,
        subtotal: true,
        subtotalWithDiscount: true,
        taxAfterDiscount: true,
        taxRate: true,
        taxWithDiscount: true,
        total: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OrderSummary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OrderSummary",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: OrderSummaryWhereUniqueInput,
    @common.Body() data: OrderSummaryUpdateInput
  ): Promise<OrderSummary | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          deliveryPrice: true,
          deliveryPriceWithDiscount: true,
          discount: true,
          driverTip: true,
          driverTipRate: true,
          id: true,
          serviceFee: true,
          serviceFeeRate: true,
          serviceFeeWithDiscount: true,
          subtotal: true,
          subtotalWithDiscount: true,
          taxAfterDiscount: true,
          taxRate: true,
          taxWithDiscount: true,
          total: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OrderSummary })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OrderSummary",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: OrderSummaryWhereUniqueInput
  ): Promise<OrderSummary | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          deliveryPrice: true,
          deliveryPriceWithDiscount: true,
          discount: true,
          driverTip: true,
          driverTipRate: true,
          id: true,
          serviceFee: true,
          serviceFeeRate: true,
          serviceFeeWithDiscount: true,
          subtotal: true,
          subtotalWithDiscount: true,
          taxAfterDiscount: true,
          taxRate: true,
          taxWithDiscount: true,
          total: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
